name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Delete existing Azure Container Instance
        run: |
          az container delete --resource-group rowling-gradproject --name rowling-backend-container3 --yes
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build -t ahmedadelabdelmohsen/rowling-gradproject:latest .
          docker push ahmedadelabdelmohsen/rowling-gradproject:latest

      - name: Update Azure Container Instances
        run: |
          az container create --resource-group rowling-gradproject --name rowling-backend-container3 --image ahmedadelabdelmohsen/rowling-gradproject:latest --dns-name-label rowling-backend3 --ports 8000 --environment-variables PORT=8000 --registry-login-server index.docker.io --registry-username ahmedadelabdelmohsen --registry-password $DOCKER_PASSWORD
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
